In [1]:
import os
import pandas as pd
os.chdir("/home/mediaworker/anaconda2/envs/pandas_playground/")
df = pd.read_csv("datasets/jamesbond.csv", index_col="Film")
df.sort_index(inplace=True)
df.head(5)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [2]:
# remove multiple index
#df.drop(['A View to a Kill', 'Die Another Day'], inplace=True)

In [3]:
# remove multiple column
df.drop(["Box Office", "Budget"], axis="columns")

# make permanent using inplace=True
#df.drop(["Box Office", "Budget"], axis="columns", inplace=True)

,Year,Actor,Director,Bond Actor Salary
Film,,,,
A View to a Kill,1985,Roger Moore,John Glen,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,3.3
Casino Royale,1967,David Niven,Ken Hughes,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,17.9
Dr. No,1962,Sean Connery,Terence Young,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,NaN
From Russia with Love,1963,Sean Connery,Terence Young,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,NaN
Octopussy,1983,Roger Moore,John Glen,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,14.5
Spectre,2015,Daniel Craig,Sam Mendes,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,13.5
Thunderball,1965,Sean Connery,Terence Young,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,4.4

In [4]:
del df["Actor"]

In [5]:
# returns removed series
df.pop("Box Office")

Film
A View to a Kill                   275.2
Casino Royale                      581.5
Casino Royale                      315.0
Diamonds Are Forever               442.5
Die Another Day                    465.4
Dr. No                             448.8
For Your Eyes Only                 449.4
From Russia with Love              543.8
GoldenEye                          518.5
Goldfinger                         820.4
Licence to Kill                    250.9
Live and Let Die                   460.3
Moonraker                          535.0
Never Say Never Again              380.0
Octopussy                          373.8
On Her Majesty's Secret Service    291.5
Quantum of Solace                  514.2
Skyfall                            943.5
Spectre                            726.7
The Living Daylights               313.5
The Man with the Golden Gun        334.0
The Spy Who Loved Me               533.0
The World Is Not Enough            439.5
Thunderball                        848.1
Tomorrow Never Dies                463.2
You Only Live Twice                514.2
Name: Box Office, dtype: float64

In [6]:
df

,Year,Director,Budget,Bond Actor Salary
Film,,,,
A View to a Kill,1985,John Glen,54.5,9.1
Casino Royale,2006,Martin Campbell,145.3,3.3
Casino Royale,1967,Ken Hughes,85.0,NaN
Diamonds Are Forever,1971,Guy Hamilton,34.7,5.8
Die Another Day,2002,Lee Tamahori,154.2,17.9
Dr. No,1962,Terence Young,7.0,0.6
For Your Eyes Only,1981,John Glen,60.2,NaN
From Russia with Love,1963,Terence Young,12.6,1.6
GoldenEye,1995,Martin Campbell,76.9,5.1
Goldfinger,1964,Guy Hamilton,18.6,3.2
Licence to Kill,1989,John Glen,56.7,7.9
Live and Let Die,1973,Guy Hamilton,30.8,NaN
Moonraker,1979,Lewis Gilbert,91.5,NaN
Never Say Never Again,1983,Irvin Kershner,86.0,NaN
Octopussy,1983,John Glen,53.9,7.8
On Her Majesty's Secret Service,1969,Peter R. Hunt,37.3,0.6
Quantum of Solace,2008,Marc Forster,181.4,8.1
Skyfall,2012,Sam Mendes,170.2,14.5
Spectre,2015,Sam Mendes,206.3,NaN
The Living Daylights,1987,John Glen,68.8,5.2
The Man with the Golden Gun,1974,Guy Hamilton,27.7,NaN
The Spy Who Loved Me,1977,Lewis Gilbert,45.1,NaN
The World Is Not Enough,1999,Michael Apted,158.3,13.5
Thunderball,1965,Terence Young,41.9,4.7
Tomorrow Never Dies,1997,Roger Spottiswoode,133.9,10.0
You Only Live Twice,1967,Lewis Gilbert,59.9,4.4